FROM node:24.15.0-alpine
WORKDIR /app
RUN apk --no-cache add curl
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/index.html ./
COPY frontend/tsconfig*.json ./
COPY frontend/vite.config.ts ./
COPY frontend/public/ public/
COPY frontend/src/ src/

CMD ["npm", "run", "dev"]
