FROM node:24.15.0-alpine AS builder
WORKDIR /app
COPY ../../backend/*.json .
RUN npm ci
COPY ../../backend/src/ .
RUN ["npm", "run", "build"]

FROM node:24.15.0-alpine
WORKDIR /app
COPY --from=builder /app/dist ./build
COPY ../../backend/package*.json .
RUN npm ci --omit=dev
CMD ["npm", "run", "start"]
