FROM node:24.15.0-alpine AS builder
WORKDIR /app
COPY ../../frontend/*.json .
COPY ../../frontend/*.html .
COPY ../../frontend/*.ts .
RUN npm ci
COPY ../../frontend/src/ src/
COPY ../../frontend/public/ public/
RUN ["npm", "run", "build"]

FROM nginx:1.31.3-alpine3.24
RUN rm -f /etc/nginx/conf.d/default.conf
COPY _env/stg/nginx/default.conf.template /etc/nginx/templates/
COPY --from=builder /app/dist /usr/share/nginx/html
