[
  {
    "id": "dev-template",
    "execute-command": "/home/ubuntu/www/apps/template/dev.deploy.sh",
    "command-working-directory": "/home/ubuntu/www/apps/template"
  },
  {
    "id": "stg-template",
    "execute-command": "/home/ubuntu/www/apps/template/stg.deploy.sh",
    "command-working-directory": "/home/ubuntu/www/apps/template"
  },
  {
    "id": "prd-template",
    "execute-command": "/home/ubuntu/www/apps/template/prd.deploy.sh",
    "command-working-directory": "/home/ubuntu/www/apps/template"
  }
]