name: Autodeploy dev environment

on:
  push:
    branches:
      - dev

jobs:
  notify-server:
    runs-on: ubuntu-latest
    environment: builder
    steps:
      - name: Notify dev server
        run: |
          curl -X GET https://hooks.${{ secrets.DOMAIN_URL }}/hooks/dev-${{ secrets.APP_NAME }}
