name: Compile Code & Send Images to DockerHub

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: builder
    strategy:
      matrix:
        service:
          - frontend
          - backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push images
        uses: docker/build-push-action@v7
        with:
          context: .
          file: _env/stg/Dockerfile.${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}-${{ matrix.service }}:latest

  notify-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: builder
    steps:
      - name: Notify staging server
        run: |
          curl -X GET https://hooks.${{ secrets.DOMAIN_URL }}/hooks/stg-${{ secrets.APP_NAME }}
