name: Autodeploy prd environment

on:
  push:
    branches:
      - main

jobs:
  notify-server:
    runs-on: ubuntu-latest
    environment: builder
    steps:
      - name: Notify prd server
        run: |
          curl -X GET https://hooks.${{ secrets.DOMAIN_URL }}/hooks/prd-${{ secrets.APP_NAME }}
